name: Auto approve
on:
 pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if:   github.event.label.name == 'auto-run'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
      
