name: Auto approve
on: 
  pull_request:
  workflow_run:
    workflows: ["Labeler"]
    types: 
         - completed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
      
