# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
      
  autoapprove:
    
    needs: label
    runs-on: ubuntu-latest
    steps:
    - name: current branch
      run: echo github.event.pull_request.labels.*.names
    - uses: hmarr/auto-approve-action@v2.0.0
       
      if: contains( toJson(github), 'auto-run' )
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        

